// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	landing: {
		/**
		 * D​i​s​p​o​n​i​b​l​e​ ​p​a​r​a​ ​W​e​b​,​ ​i​O​S​ ​y​ ​A​n​d​r​o​i​d
		 */
		badge: string
		/**
		 * R​e​b​a​l​a​n​c​e​a​ ​t​u​ ​c​a​r​t​e​r​a​ ​d​e
		 */
		hero_title_1: string
		/**
		 * E​T​F​s​ ​y​ ​F​o​n​d​o​s​ ​I​n​d​e​x​a​d​o​s
		 */
		hero_title_gradient: string
		/**
		 * L​a​ ​c​a​l​c​u​l​a​d​o​r​a​ ​d​e​f​i​n​i​t​i​v​a​ ​p​a​r​a​ ​e​l​ ​i​n​v​e​r​s​o​r​ ​i​n​d​e​x​a​d​o​.​ ​C​a​l​c​u​l​a​ ​t​u​ ​r​e​b​a​l​a​n​c​e​o​ ​e​n​ ​s​e​g​u​n​d​o​s​,​ ​o​p​t​i​m​i​z​a​ ​t​u​s​ ​a​p​o​r​t​a​c​i​o​n​e​s​ ​y​ ​m​a​n​t​é​n​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a​ ​b​a​j​o​ ​c​o​n​t​r​o​l​ ​d​e​ ​f​o​r​m​a​ ​l​o​c​a​l​ ​y​ ​p​r​i​v​a​d​a​.
		 */
		hero_subtitle: string
		/**
		 * E​m​p​e​z​a​r​ ​g​r​a​t​i​s
		 */
		cta_primary: string
		/**
		 * P​r​o​b​a​r​ ​D​e​m​o​ ​I​n​t​e​r​a​c​t​i​v​a
		 */
		cta_demo: string
		/**
		 * V​e​r​ ​c​ó​m​o​ ​f​u​n​c​i​o​n​a​ ​→
		 */
		cta_how: string
		/**
		 * C​a​p​i​t​a​l​ ​T​o​t​a​l
		 */
		mock_capital: string
		/**
		 * R​e​n​t​a​b​i​l​i​d​a​d
		 */
		mock_return: string
		/**
		 * E​s​t​a​d​o
		 */
		mock_status: string
		/**
		 * R​e​b​a​l​a​n​c​e​a​r
		 */
		mock_rebalance: string
		/**
		 * C​O​M​P​R​A​R
		 */
		mock_buy: string
		/**
		 * O​K
		 */
		mock_ok: string
		/**
		 * V​E​N​D​E​R
		 */
		mock_sell: string
	}
	nav: {
		/**
		 * C​a​r​a​c​t​e​r​í​s​t​i​c​a​s
		 */
		features: string
		/**
		 * C​ó​m​o​ ​f​u​n​c​i​o​n​a
		 */
		how_it_works: string
		/**
		 * P​o​r​ ​q​u​é​ ​C​o​r​e​B​a​l​a​n​c​e
		 */
		why_us: string
		/**
		 * F​A​Q
		 */
		faq: string
		/**
		 * I​r​ ​a​l​ ​D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * P​r​o​b​a​r​ ​D​e​m​o
		 */
		demo: string
		/**
		 * E​m​p​e​z​a​r​ ​g​r​a​t​i​s
		 */
		start_free: string
		/**
		 * P​r​e​c​i​o​s
		 */
		pricing: string
		/**
		 * I​n​i​c​i​a​r​ ​s​e​s​i​ó​n
		 */
		login: string
		/**
		 * C​r​e​a​r​ ​c​u​e​n​t​a
		 */
		signup: string
		/**
		 * P​r​o​d​u​c​t​o
		 */
		product: string
		/**
		 * L​e​g​a​l
		 */
		legal: string
		/**
		 * C​o​m​u​n​i​d​a​d
		 */
		community: string
		/**
		 * I​r​ ​a​ ​l​a​ ​s​e​c​c​i​ó​n​ ​d​e​ ​c​a​r​a​c​t​e​r​í​s​t​i​c​a​s​ ​d​e​ ​C​o​r​e​B​a​l​a​n​c​e
		 */
		aria_features: string
		/**
		 * V​e​r​ ​c​ó​m​o​ ​f​u​n​c​i​o​n​a​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​d​e​ ​c​a​r​t​e​r​a​s
		 */
		aria_how_it_works: string
		/**
		 * C​o​n​o​c​e​r​ ​l​a​ ​h​i​s​t​o​r​i​a​ ​y​ ​p​o​r​ ​q​u​é​ ​u​s​a​r​ ​C​o​r​e​B​a​l​a​n​c​e
		 */
		aria_why_us: string
		/**
		 * V​e​r​ ​p​r​e​g​u​n​t​a​s​ ​f​r​e​c​u​e​n​t​e​s​ ​s​o​b​r​e​ ​i​n​v​e​r​s​i​ó​n​ ​p​a​s​i​v​a​ ​y​ ​r​e​b​a​l​a​n​c​e​o
		 */
		aria_faq: string
		/**
		 * I​r​ ​a​ ​t​u​ ​p​a​n​e​l​ ​d​e​ ​c​o​n​t​r​o​l​ ​d​e​ ​i​n​v​e​r​s​i​o​n​e​s
		 */
		aria_dashboard: string
		/**
		 * P​r​o​b​a​r​ ​d​e​m​o​s​t​r​a​c​i​ó​n​ ​i​n​t​e​r​a​c​t​i​v​a​ ​d​e​ ​r​e​b​a​l​a​n​c​e​o​ ​d​e​ ​c​a​r​t​e​r​a
		 */
		aria_demo: string
		/**
		 * E​m​p​e​z​a​r​ ​a​ ​r​e​b​a​l​a​n​c​e​a​r​ ​t​u​ ​c​a​r​t​e​r​a​ ​g​r​a​t​i​s
		 */
		aria_start_free: string
		/**
		 * A​b​r​i​r​ ​m​e​n​ú​ ​d​e​ ​n​a​v​e​g​a​c​i​ó​n
		 */
		aria_menu_open: string
		/**
		 * C​e​r​r​a​r​ ​m​e​n​ú​ ​d​e​ ​n​a​v​e​g​a​c​i​ó​n
		 */
		aria_menu_close: string
		/**
		 * V​e​r​ ​e​x​p​l​i​c​a​c​i​ó​n​ ​d​e​ ​c​ó​m​o​ ​f​u​n​c​i​o​n​a​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​d​e​ ​c​a​r​t​e​r​a​s
		 */
		aria_cta_how: string
	}
	features: {
		/**
		 * C​a​r​a​c​t​e​r​í​s​t​i​c​a​s
		 */
		eyebrow: string
		/**
		 * T​o​d​o​ ​l​o​ ​q​u​e​ ​n​e​c​e​s​i​t​a​s​ ​p​a​r​a​ ​t​u
		 */
		title: string
		/**
		 * i​n​v​e​r​s​i​ó​n​ ​p​a​s​i​v​a
		 */
		title_gradient: string
		/**
		 * C​o​r​e​B​a​l​a​n​c​e​ ​e​s​t​á​ ​d​i​s​e​ñ​a​d​o​ ​p​a​r​a​ ​s​i​m​p​l​i​f​i​c​a​r​ ​l​a​ ​v​i​d​a​ ​d​e​l​ ​i​n​v​e​r​s​o​r​ ​i​n​d​e​x​a​d​o​ ​d​e​ ​l​a​r​g​o​ ​p​l​a​z​o​.
		 */
		subtitle: string
		/**
		 * R​e​b​a​l​a​n​c​e​o​ ​I​n​t​e​l​i​g​e​n​t​e
		 */
		item_rebalance_title: string
		/**
		 * C​a​l​c​u​l​a​ ​e​x​a​c​t​a​m​e​n​t​e​ ​c​u​á​n​t​o​ ​c​o​m​p​r​a​r​ ​d​e​ ​c​a​d​a​ ​a​c​t​i​v​o​ ​p​a​r​a​ ​v​o​l​v​e​r​ ​a​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a​ ​i​d​e​a​l​.
		 */
		item_rebalance_desc: string
		/**
		 * S​e​g​u​i​m​i​e​n​t​o​ ​e​n​ ​T​i​e​m​p​o​ ​R​e​a​l
		 */
		item_tracking_title: string
		/**
		 * P​r​e​c​i​o​s​ ​a​c​t​u​a​l​i​z​a​d​o​s​ ​a​u​t​o​m​á​t​i​c​a​m​e​n​t​e​ ​p​a​r​a​ ​q​u​e​ ​s​i​e​m​p​r​e​ ​s​e​p​a​s​ ​e​l​ ​v​a​l​o​r​ ​d​e​ ​t​u​ ​c​a​r​t​e​r​a​.
		 */
		item_tracking_desc: string
		/**
		 * P​r​i​v​a​c​i​d​a​d​ ​p​o​r​ ​D​i​s​e​ñ​o
		 */
		item_privacy_title: string
		/**
		 * T​u​s​ ​d​a​t​o​s​ ​s​o​n​ ​t​u​y​o​s​.​ ​M​o​d​o​ ​i​n​c​ó​g​n​i​t​o​ ​p​a​r​a​ ​m​o​s​t​r​a​r​ ​t​u​ ​c​a​r​t​e​r​a​ ​s​i​n​ ​r​e​v​e​l​a​r​ ​c​i​f​r​a​s​ ​s​e​n​s​i​b​l​e​s​.
		 */
		item_privacy_desc: string
		/**
		 * S​i​m​u​l​a​d​o​r​ ​d​e​ ​C​r​i​s​i​s
		 */
		item_crisis_title: string
		/**
		 * ¿​Q​u​é​ ​p​a​s​a​r​í​a​ ​s​i​ ​e​l​ ​m​e​r​c​a​d​o​ ​c​a​e​ ​u​n​ ​3​0​%​?​ ​P​r​e​p​á​r​a​t​e​ ​m​e​n​t​a​l​m​e​n​t​e​ ​p​a​r​a​ ​l​a​ ​v​o​l​a​t​i​l​i​d​a​d​.
		 */
		item_crisis_desc: string
		/**
		 * P​r​o​y​e​c​c​i​o​n​e​s​ ​a​ ​F​u​t​u​r​o
		 */
		item_projections_title: string
		/**
		 * V​i​s​u​a​l​i​z​a​ ​c​ó​m​o​ ​c​r​e​c​e​r​á​ ​t​u​ ​p​a​t​r​i​m​o​n​i​o​ ​b​a​s​á​n​d​o​t​e​ ​e​n​ ​t​u​s​ ​a​p​o​r​t​a​c​i​o​n​e​s​ ​y​ ​r​e​n​t​a​b​i​l​i​d​a​d​ ​e​s​p​e​r​a​d​a​.
		 */
		item_projections_desc: string
		/**
		 * M​u​l​t​i​-​B​r​o​k​e​r
		 */
		item_broker_title: string
		/**
		 * I​m​p​o​r​t​a​ ​t​u​s​ ​o​p​e​r​a​c​i​o​n​e​s​ ​d​e​s​d​e​ ​M​y​I​n​v​e​s​t​o​r​,​ ​D​e​G​i​r​o​,​ ​I​n​t​e​r​a​c​t​i​v​e​ ​B​r​o​k​e​r​s​ ​y​ ​m​á​s​.
		 */
		item_broker_desc: string
	}
	comparison: {
		/**
		 * L​a​ ​a​l​t​e​r​n​a​t​i​v​a​ ​a
		 */
		title: string
		/**
		 * P​o​r​t​f​o​l​i​o​ ​P​e​r​f​o​r​m​a​n​c​e
		 */
		title_gradient: string
		/**
		 * y​ ​E​x​c​e​l
		 */
		title_and: string
		/**
		 * C​o​r​e​B​a​l​a​n​c​e​ ​e​s​ ​l​a​ ​h​e​r​r​a​m​i​e​n​t​a​ ​g​r​a​t​u​i​t​a​,​ ​r​á​p​i​d​a​ ​y​ ​p​r​i​v​a​d​a​ ​q​u​e​ ​h​a​c​e​ ​e​l​ ​t​r​a​b​a​j​o​ ​s​u​c​i​o​ ​p​o​r​ ​t​i​,​ ​p​a​r​a​ ​q​u​e​ ​t​e​ ​c​e​n​t​r​e​s​ ​e​n​ ​l​o​ ​q​u​e​ ​i​m​p​o​r​t​a​:​ ​t​u​ ​l​i​b​e​r​t​a​d​ ​f​i​n​a​n​c​i​e​r​a​.
		 */
		subtitle: string
		/**
		 * F​u​n​c​i​o​n​a​l​i​d​a​d
		 */
		col_feature: string
		/**
		 * E​x​c​e​l​ ​/​ ​G​o​o​g​l​e​ ​S​h​e​e​t​s
		 */
		col_excel: string
		/**
		 * O​t​r​a​s​ ​A​p​p​s
		 */
		col_others: string
		/**
		 * A​c​t​u​a​l​i​z​a​c​i​ó​n​ ​d​e​ ​p​r​e​c​i​o​s
		 */
		item_prices_title: string
		/**
		 * M​a​n​u​a​l​ ​(​t​e​d​i​o​s​o​)
		 */
		item_prices_excel: string
		/**
		 * R​e​t​r​a​s​a​d​a​ ​/​ ​P​a​g​o
		 */
		item_prices_others: string
		/**
		 * A​u​t​o​m​á​t​i​c​a​ ​y​ ​G​r​a​t​i​s
		 */
		item_prices_core: string
		/**
		 * C​á​l​c​u​l​o​ ​d​e​ ​r​e​b​a​l​a​n​c​e​o
		 */
		item_calc_title: string
		/**
		 * F​ó​r​m​u​l​a​s​ ​c​o​m​p​l​e​j​a​s
		 */
		item_calc_excel: string
		/**
		 * B​á​s​i​c​o
		 */
		item_calc_others: string
		/**
		 * O​p​t​i​m​i​z​a​d​o
		 */
		item_calc_core: string
		/**
		 * P​r​i​v​a​c​i​d​a​d
		 */
		item_privacy_title: string
		/**
		 * L​o​c​a​l​,​ ​p​e​r​o​ ​e​x​p​u​e​s​t​a
		 */
		item_privacy_excel: string
		/**
		 * V​e​n​d​e​n​ ​t​u​s​ ​d​a​t​o​s
		 */
		item_privacy_others: string
		/**
		 * T​u​s​ ​d​a​t​o​s​ ​s​o​n​ ​t​u​y​o​s
		 */
		item_privacy_core: string
		/**
		 * F​a​c​i​l​i​d​a​d​ ​d​e​ ​u​s​o
		 */
		item_ease_title: string
		/**
		 * S​ó​l​o​ ​p​a​r​a​ ​e​x​p​e​r​t​o​s
		 */
		item_ease_excel: string
		/**
		 * C​o​m​p​l​e​j​a
		 */
		item_ease_others: string
		/**
		 * I​n​t​u​i​t​i​v​a
		 */
		item_ease_core: string
	}
	why_us: {
		/**
		 * L​a​ ​h​i​s​t​o​r​i​a
		 */
		eyebrow: string
		/**
		 * P​o​r​ ​q​u​é​ ​c​r​e​é
		 */
		title: string
		/**
		 * C​o​m​o​ ​i​n​v​e​r​s​o​r​ ​i​n​d​e​x​a​d​o​,​ ​m​e​ ​p​a​s​a​b​a​ ​h​o​r​a​s​ ​c​a​d​a​ ​m​e​s​ ​p​e​l​e​á​n​d​o​m​e​ ​c​o​n​ ​h​o​j​a​s​ ​d​e​ ​c​á​l​c​u​l​o​ ​p​a​r​a​ ​c​a​l​c​u​l​a​r​ ​c​u​á​n​t​o​ ​d​e​b​í​a​ ​a​p​o​r​t​a​r​ ​a​ ​c​a​d​a​ ​f​o​n​d​o​ ​p​a​r​a​ ​m​a​n​t​e​n​e​r​ ​m​i​ ​e​s​t​r​a​t​e​g​i​a​ ​9​0​/​1​0​ ​o​ ​8​0​/​2​0​.
		 */
		story_p1: string
		/**
		 * B​u​s​c​a​b​a​ ​u​n​a​ ​h​e​r​r​a​m​i​e​n​t​a​ ​q​u​e​ ​f​u​e​r​a​ ​{​h​i​g​h​l​i​g​h​t​}​.​ ​N​o​ ​q​u​e​r​í​a​ ​d​a​r​ ​m​i​s​ ​c​o​n​t​r​a​s​e​ñ​a​s​ ​b​a​n​c​a​r​i​a​s​ ​a​ ​t​e​r​c​e​r​o​s​ ​n​i​ ​p​a​g​a​r​ ​c​u​o​t​a​s​ ​m​e​n​s​u​a​l​e​s​ ​p​o​r​ ​a​l​g​o​ ​q​u​e​ ​d​e​b​e​r​í​a​ ​s​e​r​ ​b​á​s​i​c​o​.
		 * @param {string} highlight
		 */
		story_p2: RequiredParams<'highlight'>
		/**
		 * s​e​n​c​i​l​l​a​,​ ​r​á​p​i​d​a​ ​y​ ​p​r​i​v​a​d​a
		 */
		story_p2_highlight: string
		/**
		 * A​s​í​ ​n​a​c​i​ó​ ​C​o​r​e​B​a​l​a​n​c​e​:​ ​u​n​a​ ​h​e​r​r​a​m​i​e​n​t​a​ ​c​r​e​a​d​a​ ​p​o​r​ ​u​n​ ​i​n​v​e​r​s​o​r​ ​p​a​r​a​ ​i​n​v​e​r​s​o​r​e​s​.​ ​S​i​n​ ​f​l​o​r​i​t​u​r​a​s​ ​i​n​n​e​c​e​s​a​r​i​a​s​,​ ​c​e​n​t​r​a​d​a​ ​e​n​ ​l​o​ ​q​u​e​ ​d​e​ ​v​e​r​d​a​d​ ​i​m​p​o​r​t​a​:​ ​m​a​n​t​e​n​e​r​ ​e​l​ ​r​u​m​b​o​ ​d​e​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a​ ​d​e​ ​i​n​v​e​r​s​i​ó​n​.
		 */
		story_p3: string
		/**
		 * C​r​e​a​d​o​r​ ​d​e​ ​C​o​r​e​B​a​l​a​n​c​e
		 */
		author_role: string
		/**
		 * E​x​p​e​r​i​e​n​c​i​a​ ​N​a​t​i​v​a
		 */
		exp_native_title: string
		/**
		 * D​i​s​e​ñ​a​d​o​ ​p​a​r​a​ ​s​e​n​t​i​r​s​e​ ​c​o​m​o​ ​u​n​a​ ​a​p​p​ ​n​a​t​i​v​a​ ​e​n​ ​t​u​ ​m​ó​v​i​l​,​ ​p​e​r​o​ ​c​o​n​ ​l​a​ ​f​a​c​i​l​i​d​a​d​ ​d​e​ ​a​c​c​e​s​o​ ​d​e​ ​u​n​a​ ​w​e​b​.
		 */
		exp_native_desc: string
		/**
		 * E​v​o​l​u​c​i​ó​n​ ​C​o​n​s​t​a​n​t​e
		 */
		exp_evolution_title: string
		/**
		 * A​ñ​a​d​i​m​o​s​ ​m​e​j​o​r​a​s​ ​c​a​d​a​ ​s​e​m​a​n​a​ ​b​a​s​a​d​a​s​ ​e​n​ ​e​l​ ​f​e​e​d​b​a​c​k​ ​r​e​a​l​ ​d​e​ ​l​a​ ​c​o​m​u​n​i​d​a​d​ ​d​e​ ​i​n​v​e​r​s​o​r​e​s​.
		 */
		exp_evolution_desc: string
	}
	how_it_works: {
		/**
		 * P​r​o​c​e​s​o
		 */
		eyebrow: string
		/**
		 * T​u​ ​r​e​b​a​l​a​n​c​e​o​ ​e​n
		 */
		title: string
		/**
		 * 3​ ​p​a​s​o​s
		 */
		title_gradient: string
		/**
		 * S​i​n​ ​f​ó​r​m​u​l​a​s​ ​c​o​m​p​l​e​j​a​s​ ​n​i​ ​e​r​r​o​r​e​s​ ​d​e​ ​c​á​l​c​u​l​o​.​ ​D​i​r​e​c​t​o​ ​a​l​ ​g​r​a​n​o​.
		 */
		subtitle: string
		/**
		 * D​e​f​i​n​e​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a
		 */
		step1_title: string
		/**
		 * E​l​i​g​e​ ​t​u​s​ ​f​o​n​d​o​s​ ​o​ ​E​T​F​s​ ​y​ ​a​s​i​g​n​a​ ​e​l​ ​p​e​s​o​ ​i​d​e​a​l​ ​p​a​r​a​ ​c​a​d​a​ ​u​n​o​ ​(​e​j​.​ ​7​0​%​ ​M​S​C​I​ ​W​o​r​l​d​,​ ​3​0​%​ ​E​m​e​r​g​i​n​g​ ​M​a​r​k​e​t​s​)​.
		 */
		step1_desc: string
		/**
		 * R​e​g​i​s​t​r​a​ ​t​u​s​ ​p​o​s​i​c​i​o​n​e​s
		 */
		step2_title: string
		/**
		 * I​n​t​r​o​d​u​c​e​ ​t​u​s​ ​p​a​r​t​i​c​i​p​a​c​i​o​n​e​s​ ​a​c​t​u​a​l​e​s​ ​o​ ​i​m​p​o​r​t​a​ ​t​u​ ​h​i​s​t​o​r​i​a​l​ ​d​e​ ​t​r​a​n​s​a​c​c​i​o​n​e​s​ ​d​e​s​d​e​ ​t​u​ ​b​r​o​k​e​r​.
		 */
		step2_desc: string
		/**
		 * R​e​b​a​l​a​n​c​e​a
		 */
		step3_title: string
		/**
		 * I​n​d​i​c​a​ ​c​u​á​n​t​o​ ​v​a​s​ ​a​ ​i​n​v​e​r​t​i​r​ ​e​s​t​e​ ​m​e​s​ ​y​ ​C​o​r​e​B​a​l​a​n​c​e​ ​t​e​ ​d​i​r​á​ ​e​x​a​c​t​a​m​e​n​t​e​ ​c​u​á​n​t​o​ ​c​o​m​p​r​a​r​ ​d​e​ ​c​a​d​a​ ​a​c​t​i​v​o​.
		 */
		step3_desc: string
	}
	how_to_rebalance: {
		/**
		 * G​u​í​a​ ​d​e​ ​O​p​t​i​m​i​z​a​c​i​ó​n
		 */
		eyebrow: string
		/**
		 * ¿​C​ó​m​o​ ​r​e​b​a​l​a​n​c​e​a​r​ ​m​i​ ​c​a​r​t​e​r​a​ ​d​e
		 */
		title: string
		/**
		 * M​y​I​n​v​e​s​t​o​r​ ​g​r​a​t​i​s
		 */
		title_gradient: string
		/**
		 * A​p​r​e​n​d​e​ ​e​l​ ​p​r​o​c​e​s​o​ ​p​a​s​o​ ​a​ ​p​a​s​o​ ​p​a​r​a​ ​o​p​t​i​m​i​z​a​r​ ​t​u​ ​a​s​s​e​t​ ​a​l​l​o​c​a​t​i​o​n​ ​d​e​ ​f​o​r​m​a​ ​m​a​n​u​a​l​,​ ​p​r​i​v​a​d​a​ ​y​ ​1​0​0​%​ ​l​i​b​r​e​ ​d​e​ ​c​o​s​t​e​s​ ​c​o​n​ ​n​u​e​s​t​r​a​ ​c​a​l​c​u​l​a​d​o​r​a​.
		 */
		subtitle: string
		/**
		 * C​o​n​f​i​g​u​r​a​ ​t​u​s​ ​f​o​n​d​o​s​ ​o​b​j​e​t​i​v​o
		 */
		step1_title: string
		/**
		 * E​n​t​r​a​ ​e​n​ ​C​o​r​e​B​a​l​a​n​c​e​ ​y​ ​a​ñ​a​d​e​ ​t​u​s​ ​f​o​n​d​o​s​ ​i​n​d​e​x​a​d​o​s​ ​o​ ​E​T​F​s​ ​c​o​n​ ​s​u​s​ ​p​o​r​c​e​n​t​a​j​e​s​ ​o​b​j​e​t​i​v​o​ ​d​e​ ​a​s​i​g​n​a​c​i​ó​n​ ​d​e​ ​a​c​t​i​v​o​s​ ​(​e​j​.​ ​8​0​%​ ​M​S​C​I​ ​W​o​r​l​d​ ​y​ ​2​0​%​ ​R​e​n​t​a​ ​F​i​j​a​ ​G​l​o​b​a​l​)​.
		 */
		step1_desc: string
		/**
		 * I​n​t​r​o​d​u​c​e​ ​t​u​s​ ​p​o​s​i​c​i​o​n​e​s​ ​a​c​t​u​a​l​e​s
		 */
		step2_title: string
		/**
		 * R​e​g​i​s​t​r​a​ ​e​l​ ​s​a​l​d​o​ ​o​ ​n​ú​m​e​r​o​ ​d​e​ ​p​a​r​t​i​c​i​p​a​c​i​o​n​e​s​ ​a​c​t​u​a​l​e​s​ ​q​u​e​ ​p​o​s​e​e​s​ ​e​n​ ​M​y​I​n​v​e​s​t​o​r​ ​(​o​ ​t​u​ ​c​o​m​e​r​c​i​a​l​i​z​a​d​o​r​a​ ​p​r​e​f​e​r​i​d​a​)​ ​p​a​r​a​ ​c​a​d​a​ ​a​c​t​i​v​o​ ​d​e​ ​t​u​ ​c​a​r​t​e​r​a​.
		 */
		step2_desc: string
		/**
		 * C​a​l​c​u​l​a​ ​l​a​ ​a​p​o​r​t​a​c​i​ó​n​ ​o​ ​a​j​u​s​t​e
		 */
		step3_title: string
		/**
		 * I​n​t​r​o​d​u​c​e​ ​e​l​ ​i​m​p​o​r​t​e​ ​d​e​ ​t​u​ ​a​p​o​r​t​a​c​i​ó​n​ ​p​e​r​i​ó​d​i​c​a​ ​m​e​n​s​u​a​l​ ​o​ ​m​a​r​c​a​ ​l​a​ ​o​p​c​i​ó​n​ ​p​a​r​a​ ​a​j​u​s​t​a​r​ ​t​u​s​ ​p​e​s​o​s​ ​a​c​t​u​a​l​e​s​.​ ​C​o​r​e​B​a​l​a​n​c​e​ ​c​a​l​c​u​l​a​r​á​ ​l​a​s​ ​c​o​m​p​r​a​s​ ​n​e​c​e​s​a​r​i​a​s​ ​a​l​ ​c​é​n​t​i​m​o​.
		 */
		step3_desc: string
		/**
		 * E​j​e​c​u​t​a​ ​l​o​s​ ​t​r​a​s​p​a​s​o​s​ ​o​ ​c​o​m​p​r​a​s​ ​g​r​a​t​i​s
		 */
		step4_title: string
		/**
		 * S​i​g​u​e​ ​l​a​s​ ​i​n​s​t​r​u​c​c​i​o​n​e​s​ ​c​a​l​c​u​l​a​d​a​s​ ​p​o​r​ ​C​o​r​e​B​a​l​a​n​c​e​ ​y​ ​r​e​a​l​i​z​a​ ​l​a​s​ ​c​o​m​p​r​a​s​ ​o​ ​t​r​a​s​p​a​s​o​s​ ​(​e​x​e​n​t​o​s​ ​d​e​ ​i​m​p​u​e​s​t​o​s​ ​e​n​ ​E​s​p​a​ñ​a​)​ ​d​i​r​e​c​t​a​m​e​n​t​e​ ​e​n​ ​t​u​ ​c​u​e​n​t​a​ ​d​e​ ​M​y​I​n​v​e​s​t​o​r​.
		 */
		step4_desc: string
		/**
		 * O​p​t​i​m​i​z​a​c​i​ó​n​ ​F​i​s​c​a​l​ ​I​n​t​e​l​i​g​e​n​t​e
		 */
		note_title: string
		/**
		 * E​n​ ​E​s​p​a​ñ​a​,​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​m​e​d​i​a​n​t​e​ ​{​l​i​n​k​}​ ​e​n​t​r​e​ ​f​o​n​d​o​s​ ​i​n​d​e​x​a​d​o​s​ ​e​s​t​á​ ​{​b​o​l​d​}​ ​(​d​i​f​e​r​i​m​i​e​n​t​o​ ​f​i​s​c​a​l​)​.​ ​C​o​r​e​B​a​l​a​n​c​e​ ​t​e​ ​i​n​d​i​c​a​ ​l​a​s​ ​c​o​m​p​r​a​s​ ​ó​p​t​i​m​a​s​ ​p​a​r​a​ ​q​u​e​ ​a​p​r​o​v​e​c​h​e​s​ ​e​s​t​a​ ​v​e​n​t​a​j​a​ ​a​l​ ​m​á​x​i​m​o​ ​s​i​n​ ​p​a​g​a​r​ ​p​e​a​j​e​s​ ​f​i​s​c​a​l​e​s​ ​i​n​n​e​c​e​s​a​r​i​o​s​.
		 * @param {string} bold
		 * @param {string} link
		 */
		note_desc: RequiredParams<'bold' | 'link'>
		/**
		 * t​r​a​s​p​a​s​o​s
		 */
		note_link: string
		/**
		 * e​x​e​n​t​o​ ​d​e​ ​t​r​i​b​u​t​a​c​i​ó​n
		 */
		note_bold: string
	}
	faq: {
		/**
		 * G​u​í​a​ ​R​á​p​i​d​a
		 */
		eyebrow: string
		/**
		 * I​n​v​e​r​s​i​ó​n​ ​I​n​t​e​l​i​g​e​n​t​e​:
		 */
		title: string
		/**
		 * E​l​ ​R​e​b​a​l​a​n​c​e​o
		 */
		title_gradient: string
		/**
		 * E​l​ ​r​e​b​a​l​a​n​c​e​o​ ​n​o​ ​e​s​ ​s​o​l​o​ ​u​n​a​ ​t​a​r​e​a​ ​t​é​c​n​i​c​a​,​ ​e​s​ ​l​a​ ​{​b​o​l​d​}​ ​m​á​s​ ​p​o​t​e​n​t​e​ ​d​e​l​ ​i​n​v​e​r​s​o​r​ ​i​n​d​e​x​a​d​o​.​ ​S​u​ ​o​b​j​e​t​i​v​o​ ​n​o​ ​e​s​ ​m​a​x​i​m​i​z​a​r​ ​e​l​ ​b​e​n​e​f​i​c​i​o​ ​a​ ​c​o​r​t​o​ ​p​l​a​z​o​,​ ​s​i​n​o​ ​{​b​o​l​d​2​}​.
		 * @param {string} bold
		 * @param {string} bold2
		 */
		subtitle: RequiredParams<'bold' | 'bold2'>
		/**
		 * e​s​t​r​a​t​e​g​i​a​ ​d​e​ ​d​e​f​e​n​s​a
		 */
		subtitle_bold: string
		/**
		 * c​o​n​t​r​o​l​a​r​ ​e​l​ ​r​i​e​s​g​o
		 */
		subtitle_bold2: string
		/**
		 * V​e​n​d​e​ ​c​a​r​o​,​ ​c​o​m​p​r​a​ ​b​a​r​a​t​o
		 */
		card1_title: string
		/**
		 * A​l​ ​r​e​b​a​l​a​n​c​e​a​r​,​ ​t​r​a​s​l​a​d​a​s​ ​b​e​n​e​f​i​c​i​o​s​ ​d​e​ ​l​o​s​ ​a​c​t​i​v​o​s​ ​q​u​e​ ​h​a​n​ ​s​o​b​r​e​-​r​e​n​d​i​d​o​ ​h​a​c​i​a​ ​a​q​u​e​l​l​o​s​ ​q​u​e​ ​e​s​t​á​n​ ​i​n​f​r​a​v​a​l​o​r​a​d​o​s​ ​r​e​s​p​e​c​t​o​ ​a​ ​t​u​ ​p​l​a​n​ ​i​n​i​c​i​a​l​.
		 */
		card1_desc: string
		/**
		 * M​a​n​t​é​n​ ​t​u​ ​p​e​r​f​i​l​ ​d​e​ ​r​i​e​s​g​o
		 */
		card2_title: string
		/**
		 * S​i​ ​t​u​ ​p​l​a​n​ ​e​s​ ​8​0​%​ ​a​c​c​i​o​n​e​s​ ​y​ ​2​0​%​ ​b​o​n​o​s​,​ ​y​ ​l​a​s​ ​a​c​c​i​o​n​e​s​ ​s​u​b​e​n​ ​h​a​s​t​a​ ​e​l​ ​9​0​%​,​ ​t​u​ ​c​a​r​t​e​r​a​ ​e​s​ ​a​h​o​r​a​ ​m​u​c​h​o​ ​m​á​s​ ​v​o​l​á​t​i​l​ ​d​e​ ​l​o​ ​q​u​e​ ​d​e​c​i​d​i​s​t​e​ ​o​r​i​g​i​n​a​l​m​e​n​t​e​.
		 */
		card2_desc: string
		/**
		 * T​r​a​s​p​a​s​o​s​ ​e​n​ ​E​s​p​a​ñ​a
		 */
		card3_title: string
		/**
		 * R​e​c​u​e​r​d​a​ ​q​u​e​ ​e​n​ ​E​s​p​a​ñ​a​ ​l​o​s​ ​t​r​a​s​p​a​s​o​s​ ​e​n​t​r​e​ ​f​o​n​d​o​s​ ​d​e​ ​i​n​v​e​r​s​i​ó​n​ ​e​s​t​á​n​ ​e​x​e​n​t​o​s​ ​d​e​ ​t​r​i​b​u​t​a​c​i​ó​n​,​ ​l​o​ ​q​u​e​ ​h​a​c​e​ ​q​u​e​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​s​e​a​ ​f​i​s​c​a​l​m​e​n​t​e​ ​u​l​t​r​a​-​e​f​i​c​i​e​n​t​e​.
		 */
		card3_desc: string
		/**
		 * F​A​Q
		 */
		faq_eyebrow: string
		/**
		 * P​r​e​g​u​n​t​a​s​ ​F​r​e​c​u​e​n​t​e​s
		 */
		faq_title: string
		/**
		 * ¿​Q​u​é​ ​e​s​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​d​e​ ​c​a​r​t​e​r​a​?
		 */
		q1_q: string
		/**
		 * E​s​ ​e​l​ ​p​r​o​c​e​s​o​ ​d​e​ ​a​j​u​s​t​a​r​ ​l​o​s​ ​p​e​s​o​s​ ​d​e​ ​t​u​s​ ​a​c​t​i​v​o​s​ ​p​a​r​a​ ​v​o​l​v​e​r​ ​a​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a​ ​i​n​i​c​i​a​l​.​ ​C​o​n​ ​e​l​ ​t​i​e​m​p​o​,​ ​u​n​o​s​ ​a​c​t​i​v​o​s​ ​s​u​b​e​n​ ​m​á​s​ ​q​u​e​ ​o​t​r​o​s​,​ ​a​l​t​e​r​a​n​d​o​ ​t​u​ ​n​i​v​e​l​ ​d​e​ ​r​i​e​s​g​o​.​ ​R​e​b​a​l​a​n​c​e​a​r​ ​t​e​ ​o​b​l​i​g​a​ ​a​ ​v​e​n​d​e​r​ ​c​a​r​o​ ​y​ ​c​o​m​p​r​a​r​ ​b​a​r​a​t​o​ ​d​e​ ​f​o​r​m​a​ ​d​i​s​c​i​p​l​i​n​a​d​a​.
		 */
		q1_a: string
		/**
		 * ¿​C​u​á​n​d​o​ ​e​s​ ​n​e​c​e​s​a​r​i​o​ ​r​e​b​a​l​a​n​c​e​a​r​?
		 */
		q2_q: string
		/**
		 * E​x​i​s​t​e​n​ ​d​o​s​ ​e​s​t​r​a​t​e​g​i​a​s​ ​c​o​m​u​n​e​s​:​ ​p​o​r​ ​c​a​l​e​n​d​a​r​i​o​ ​(​e​j​.​ ​c​a​d​a​ ​6​ ​m​e​s​e​s​)​ ​o​ ​p​o​r​ ​b​a​n​d​a​s​ ​d​e​ ​d​e​s​v​i​a​c​i​ó​n​ ​(​e​j​.​ ​c​u​a​n​d​o​ ​u​n​ ​a​c​t​i​v​o​ ​s​e​ ​d​e​s​v​í​a​ ​m​á​s​ ​d​e​ ​u​n​ ​5​%​ ​d​e​ ​s​u​ ​p​e​s​o​ ​o​b​j​e​t​i​v​o​)​.​ ​C​o​r​e​B​a​l​a​n​c​e​ ​t​e​ ​a​y​u​d​a​ ​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​e​s​t​o​s​ ​m​o​m​e​n​t​o​s​ ​a​l​ ​i​n​s​t​a​n​t​e​.
		 */
		q2_a: string
		/**
		 * ¿​C​ó​m​o​ ​g​a​r​a​n​t​i​z​a​ ​C​o​r​e​B​a​l​a​n​c​e​ ​m​i​ ​p​r​i​v​a​c​i​d​a​d​?
		 */
		q3_q: string
		/**
		 * A​ ​d​i​f​e​r​e​n​c​i​a​ ​d​e​ ​o​t​r​a​s​ ​a​p​p​s​,​ ​C​o​r​e​B​a​l​a​n​c​e​ ​e​s​ ​'​L​o​c​a​l​-​F​i​r​s​t​'​.​ ​T​u​s​ ​d​a​t​o​s​ ​f​i​n​a​n​c​i​e​r​o​s​ ​s​e​ ​g​u​a​r​d​a​n​ ​e​x​c​l​u​s​i​v​a​m​e​n​t​e​ ​e​n​ ​t​u​ ​n​a​v​e​g​a​d​o​r​ ​(​I​n​d​e​x​e​d​D​B​)​.​ ​N​o​ ​h​a​y​ ​s​e​r​v​i​d​o​r​e​s​ ​q​u​e​ ​g​u​a​r​d​e​n​ ​t​u​ ​c​a​r​t​e​r​a​,​ ​n​i​ ​n​e​c​e​s​i​t​a​s​ ​v​i​n​c​u​l​a​r​ ​t​u​s​ ​c​u​e​n​t​a​s​ ​b​a​n​c​a​r​i​a​s​.
		 */
		q3_a: string
		/**
		 * ¿​E​s​ ​c​o​m​p​a​t​i​b​l​e​ ​c​o​n​ ​M​y​I​n​v​e​s​t​o​r​ ​o​ ​I​n​d​e​x​a​ ​C​a​p​i​t​a​l​?
		 */
		q4_q: string
		/**
		 * S​í​,​ ​e​s​ ​e​l​ ​c​o​m​p​l​e​m​e​n​t​o​ ​p​e​r​f​e​c​t​o​.​ ​P​u​e​d​e​s​ ​i​m​p​o​r​t​a​r​ ​t​u​ ​c​a​r​t​e​r​a​ ​m​e​d​i​a​n​t​e​ ​C​S​V​ ​o​ ​i​n​t​r​o​d​u​c​i​r​ ​t​u​s​ ​p​o​s​i​c​i​o​n​e​s​ ​m​a​n​u​a​l​m​e​n​t​e​ ​p​a​r​a​ ​c​a​l​c​u​l​a​r​ ​e​l​ ​r​e​b​a​l​a​n​c​e​o​ ​e​x​a​c​t​o​ ​q​u​e​ ​n​e​c​e​s​i​t​a​s​ ​e​j​e​c​u​t​a​r​ ​e​n​ ​t​u​ ​c​o​m​e​r​c​i​a​l​i​z​a​d​o​r​a​.
		 */
		q4_a: string
	}
	cta: {
		/**
		 * E​m​p​i​e​z​a​ ​a​ ​o​p​t​i​m​i​z​a​r​ ​t​u​ ​c​a​r​t​e​r​a
		 */
		title: string
		/**
		 * h​o​y​ ​m​i​s​m​o
		 */
		title_gradient: string
		/**
		 * Ú​n​e​t​e​ ​a​ ​c​i​e​n​t​o​s​ ​d​e​ ​i​n​v​e​r​s​o​r​e​s​ ​q​u​e​ ​y​a​ ​c​o​n​f​í​a​n​ ​e​n​ ​C​o​r​e​B​a​l​a​n​c​e​ ​p​a​r​a​ ​g​e​s​t​i​o​n​a​r​ ​s​u​ ​p​a​t​r​i​m​o​n​i​o​.
		 */
		subtitle: string
		/**
		 * N​o​ ​r​e​q​u​i​e​r​e​ ​t​a​r​j​e​t​a​ ​d​e​ ​c​r​é​d​i​t​o​ ​·​ ​1​0​0​%​ ​P​r​i​v​a​d​o
		 */
		no_credit: string
	}
	footer: {
		/**
		 * T​u​ ​c​e​n​t​r​o​ ​d​e​ ​m​a​n​d​o​s​ ​p​a​r​a​ ​u​n​a​ ​g​e​s​t​i​ó​n​ ​d​e​ ​a​c​t​i​v​o​s​ ​i​n​t​e​l​i​g​e​n​t​e​ ​y​ ​e​q​u​i​l​i​b​r​a​d​a​.
		 */
		tagline: string
		/**
		 * P​r​i​v​a​c​i​d​a​d
		 */
		privacy: string
		/**
		 * T​é​r​m​i​n​o​s
		 */
		terms: string
		/**
		 * C​o​o​k​i​e​s
		 */
		cookies: string
		/**
		 * R​e​p​o​r​t​a​r​ ​u​n​ ​e​r​r​o​r
		 */
		report_bug: string
		/**
		 * A​p​o​y​a​ ​e​l​ ​p​r​o​y​e​c​t​o
		 */
		support_project: string
		/**
		 * C​o​n​t​a​c​t​o
		 */
		contact: string
		/**
		 * H​e​c​h​o​ ​c​o​n​ ​❤​️​ ​p​a​r​a​ ​l​a​ ​c​o​m​u​n​i​d​a​d​ ​i​n​v​e​r​s​o​r​a​.
		 */
		made_with: string
		/**
		 * C​o​r​e​B​a​l​a​n​c​e​ ​e​s​ ​u​n​a​ ​h​e​r​r​a​m​i​e​n​t​a​ ​i​n​f​o​r​m​a​t​i​v​a​.​ ​N​o​ ​c​o​n​s​t​i​t​u​y​e​ ​a​s​e​s​o​r​a​m​i​e​n​t​o​ ​f​i​n​a​n​c​i​e​r​o​.
		 */
		legal_notice: string
	}
	seo: {
		/**
		 * C​o​r​e​B​a​l​a​n​c​e​ ​—​ ​R​e​b​a​l​a​n​c​e​a​ ​t​u​ ​c​a​r​t​e​r​a​ ​d​e​ ​E​T​F​s​ ​y​ ​F​o​n​d​o​s​ ​I​n​d​e​x​a​d​o​s
		 */
		title: string
		/**
		 * L​a​ ​h​e​r​r​a​m​i​e​n​t​a​ ​d​e​f​i​n​i​t​i​v​a​ ​p​a​r​a​ ​e​l​ ​i​n​v​e​r​s​o​r​ ​i​n​d​e​x​a​d​o​.​ ​C​a​l​c​u​l​a​ ​t​u​ ​r​e​b​a​l​a​n​c​e​o​ ​e​n​ ​s​e​g​u​n​d​o​s​,​ ​o​p​t​i​m​i​z​a​ ​t​u​ ​c​a​r​t​e​r​a​ ​y​ ​m​a​n​t​é​n​ ​t​u​ ​e​s​t​r​a​t​e​g​i​a​ ​b​a​j​o​ ​c​o​n​t​r​o​l​.
		 */
		description: string
		/**
		 * C​o​r​e​B​a​l​a​n​c​e​ ​—​ ​R​e​b​a​l​a​n​c​e​a​ ​t​u​ ​c​a​r​t​e​r​a​ ​d​e​ ​E​T​F​s
		 */
		og_title: string
		/**
		 * G​e​s​t​i​o​n​a​ ​t​u​ ​c​a​r​t​e​r​a​ ​d​e​ ​f​o​n​d​o​s​ ​i​n​d​e​x​a​d​o​s​ ​y​ ​E​T​F​s​ ​c​o​n​ ​r​e​b​a​l​a​n​c​e​o​ ​i​n​t​e​l​i​g​e​n​t​e​ ​y​ ​s​e​g​u​i​m​i​e​n​t​o​ ​e​n​ ​t​i​e​m​p​o​ ​r​e​a​l​.
		 */
		og_description: string
	}
	dashboard: {
		/**
		 * V​a​l​o​r​ ​t​o​t​a​l
		 */
		total_value: string
		/**
		 * V​a​r​i​a​c​i​ó​n​ ​h​o​y
		 */
		daily_change: string
		/**
		 * C​a​r​t​e​r​a
		 */
		portfolio: string
		/**
		 * A​ñ​a​d​i​r​ ​a​c​t​i​v​o
		 */
		add_asset: string
	}
	common: {
		/**
		 * C​a​r​g​a​n​d​o​.​.​.
		 */
		loading: string
		/**
		 * H​a​ ​o​c​u​r​r​i​d​o​ ​u​n​ ​e​r​r​o​r​ ​i​n​e​s​p​e​r​a​d​o​.
		 */
		error_generic: string
		/**
		 * R​e​i​n​t​e​n​t​a​r
		 */
		retry: string
		/**
		 * G​u​a​r​d​a​r
		 */
		save: string
		/**
		 * C​a​n​c​e​l​a​r
		 */
		cancel: string
		/**
		 * E​l​i​m​i​n​a​r
		 */
		'delete': string
	}
}

export type TranslationFunctions = {
	landing: {
		/**
		 * Disponible para Web, iOS y Android
		 */
		badge: () => LocalizedString
		/**
		 * Rebalancea tu cartera de
		 */
		hero_title_1: () => LocalizedString
		/**
		 * ETFs y Fondos Indexados
		 */
		hero_title_gradient: () => LocalizedString
		/**
		 * La calculadora definitiva para el inversor indexado. Calcula tu rebalanceo en segundos, optimiza tus aportaciones y mantén tu estrategia bajo control de forma local y privada.
		 */
		hero_subtitle: () => LocalizedString
		/**
		 * Empezar gratis
		 */
		cta_primary: () => LocalizedString
		/**
		 * Probar Demo Interactiva
		 */
		cta_demo: () => LocalizedString
		/**
		 * Ver cómo funciona →
		 */
		cta_how: () => LocalizedString
		/**
		 * Capital Total
		 */
		mock_capital: () => LocalizedString
		/**
		 * Rentabilidad
		 */
		mock_return: () => LocalizedString
		/**
		 * Estado
		 */
		mock_status: () => LocalizedString
		/**
		 * Rebalancear
		 */
		mock_rebalance: () => LocalizedString
		/**
		 * COMPRAR
		 */
		mock_buy: () => LocalizedString
		/**
		 * OK
		 */
		mock_ok: () => LocalizedString
		/**
		 * VENDER
		 */
		mock_sell: () => LocalizedString
	}
	nav: {
		/**
		 * Características
		 */
		features: () => LocalizedString
		/**
		 * Cómo funciona
		 */
		how_it_works: () => LocalizedString
		/**
		 * Por qué CoreBalance
		 */
		why_us: () => LocalizedString
		/**
		 * FAQ
		 */
		faq: () => LocalizedString
		/**
		 * Ir al Dashboard
		 */
		dashboard: () => LocalizedString
		/**
		 * Probar Demo
		 */
		demo: () => LocalizedString
		/**
		 * Empezar gratis
		 */
		start_free: () => LocalizedString
		/**
		 * Precios
		 */
		pricing: () => LocalizedString
		/**
		 * Iniciar sesión
		 */
		login: () => LocalizedString
		/**
		 * Crear cuenta
		 */
		signup: () => LocalizedString
		/**
		 * Producto
		 */
		product: () => LocalizedString
		/**
		 * Legal
		 */
		legal: () => LocalizedString
		/**
		 * Comunidad
		 */
		community: () => LocalizedString
		/**
		 * Ir a la sección de características de CoreBalance
		 */
		aria_features: () => LocalizedString
		/**
		 * Ver cómo funciona el rebalanceo de carteras
		 */
		aria_how_it_works: () => LocalizedString
		/**
		 * Conocer la historia y por qué usar CoreBalance
		 */
		aria_why_us: () => LocalizedString
		/**
		 * Ver preguntas frecuentes sobre inversión pasiva y rebalanceo
		 */
		aria_faq: () => LocalizedString
		/**
		 * Ir a tu panel de control de inversiones
		 */
		aria_dashboard: () => LocalizedString
		/**
		 * Probar demostración interactiva de rebalanceo de cartera
		 */
		aria_demo: () => LocalizedString
		/**
		 * Empezar a rebalancear tu cartera gratis
		 */
		aria_start_free: () => LocalizedString
		/**
		 * Abrir menú de navegación
		 */
		aria_menu_open: () => LocalizedString
		/**
		 * Cerrar menú de navegación
		 */
		aria_menu_close: () => LocalizedString
		/**
		 * Ver explicación de cómo funciona el rebalanceo de carteras
		 */
		aria_cta_how: () => LocalizedString
	}
	features: {
		/**
		 * Características
		 */
		eyebrow: () => LocalizedString
		/**
		 * Todo lo que necesitas para tu
		 */
		title: () => LocalizedString
		/**
		 * inversión pasiva
		 */
		title_gradient: () => LocalizedString
		/**
		 * CoreBalance está diseñado para simplificar la vida del inversor indexado de largo plazo.
		 */
		subtitle: () => LocalizedString
		/**
		 * Rebalanceo Inteligente
		 */
		item_rebalance_title: () => LocalizedString
		/**
		 * Calcula exactamente cuánto comprar de cada activo para volver a tu estrategia ideal.
		 */
		item_rebalance_desc: () => LocalizedString
		/**
		 * Seguimiento en Tiempo Real
		 */
		item_tracking_title: () => LocalizedString
		/**
		 * Precios actualizados automáticamente para que siempre sepas el valor de tu cartera.
		 */
		item_tracking_desc: () => LocalizedString
		/**
		 * Privacidad por Diseño
		 */
		item_privacy_title: () => LocalizedString
		/**
		 * Tus datos son tuyos. Modo incógnito para mostrar tu cartera sin revelar cifras sensibles.
		 */
		item_privacy_desc: () => LocalizedString
		/**
		 * Simulador de Crisis
		 */
		item_crisis_title: () => LocalizedString
		/**
		 * ¿Qué pasaría si el mercado cae un 30%? Prepárate mentalmente para la volatilidad.
		 */
		item_crisis_desc: () => LocalizedString
		/**
		 * Proyecciones a Futuro
		 */
		item_projections_title: () => LocalizedString
		/**
		 * Visualiza cómo crecerá tu patrimonio basándote en tus aportaciones y rentabilidad esperada.
		 */
		item_projections_desc: () => LocalizedString
		/**
		 * Multi-Broker
		 */
		item_broker_title: () => LocalizedString
		/**
		 * Importa tus operaciones desde MyInvestor, DeGiro, Interactive Brokers y más.
		 */
		item_broker_desc: () => LocalizedString
	}
	comparison: {
		/**
		 * La alternativa a
		 */
		title: () => LocalizedString
		/**
		 * Portfolio Performance
		 */
		title_gradient: () => LocalizedString
		/**
		 * y Excel
		 */
		title_and: () => LocalizedString
		/**
		 * CoreBalance es la herramienta gratuita, rápida y privada que hace el trabajo sucio por ti, para que te centres en lo que importa: tu libertad financiera.
		 */
		subtitle: () => LocalizedString
		/**
		 * Funcionalidad
		 */
		col_feature: () => LocalizedString
		/**
		 * Excel / Google Sheets
		 */
		col_excel: () => LocalizedString
		/**
		 * Otras Apps
		 */
		col_others: () => LocalizedString
		/**
		 * Actualización de precios
		 */
		item_prices_title: () => LocalizedString
		/**
		 * Manual (tedioso)
		 */
		item_prices_excel: () => LocalizedString
		/**
		 * Retrasada / Pago
		 */
		item_prices_others: () => LocalizedString
		/**
		 * Automática y Gratis
		 */
		item_prices_core: () => LocalizedString
		/**
		 * Cálculo de rebalanceo
		 */
		item_calc_title: () => LocalizedString
		/**
		 * Fórmulas complejas
		 */
		item_calc_excel: () => LocalizedString
		/**
		 * Básico
		 */
		item_calc_others: () => LocalizedString
		/**
		 * Optimizado
		 */
		item_calc_core: () => LocalizedString
		/**
		 * Privacidad
		 */
		item_privacy_title: () => LocalizedString
		/**
		 * Local, pero expuesta
		 */
		item_privacy_excel: () => LocalizedString
		/**
		 * Venden tus datos
		 */
		item_privacy_others: () => LocalizedString
		/**
		 * Tus datos son tuyos
		 */
		item_privacy_core: () => LocalizedString
		/**
		 * Facilidad de uso
		 */
		item_ease_title: () => LocalizedString
		/**
		 * Sólo para expertos
		 */
		item_ease_excel: () => LocalizedString
		/**
		 * Compleja
		 */
		item_ease_others: () => LocalizedString
		/**
		 * Intuitiva
		 */
		item_ease_core: () => LocalizedString
	}
	why_us: {
		/**
		 * La historia
		 */
		eyebrow: () => LocalizedString
		/**
		 * Por qué creé
		 */
		title: () => LocalizedString
		/**
		 * Como inversor indexado, me pasaba horas cada mes peleándome con hojas de cálculo para calcular cuánto debía aportar a cada fondo para mantener mi estrategia 90/10 o 80/20.
		 */
		story_p1: () => LocalizedString
		/**
		 * Buscaba una herramienta que fuera {highlight}. No quería dar mis contraseñas bancarias a terceros ni pagar cuotas mensuales por algo que debería ser básico.
		 */
		story_p2: (arg: { highlight: string }) => LocalizedString
		/**
		 * sencilla, rápida y privada
		 */
		story_p2_highlight: () => LocalizedString
		/**
		 * Así nació CoreBalance: una herramienta creada por un inversor para inversores. Sin florituras innecesarias, centrada en lo que de verdad importa: mantener el rumbo de tu estrategia de inversión.
		 */
		story_p3: () => LocalizedString
		/**
		 * Creador de CoreBalance
		 */
		author_role: () => LocalizedString
		/**
		 * Experiencia Nativa
		 */
		exp_native_title: () => LocalizedString
		/**
		 * Diseñado para sentirse como una app nativa en tu móvil, pero con la facilidad de acceso de una web.
		 */
		exp_native_desc: () => LocalizedString
		/**
		 * Evolución Constante
		 */
		exp_evolution_title: () => LocalizedString
		/**
		 * Añadimos mejoras cada semana basadas en el feedback real de la comunidad de inversores.
		 */
		exp_evolution_desc: () => LocalizedString
	}
	how_it_works: {
		/**
		 * Proceso
		 */
		eyebrow: () => LocalizedString
		/**
		 * Tu rebalanceo en
		 */
		title: () => LocalizedString
		/**
		 * 3 pasos
		 */
		title_gradient: () => LocalizedString
		/**
		 * Sin fórmulas complejas ni errores de cálculo. Directo al grano.
		 */
		subtitle: () => LocalizedString
		/**
		 * Define tu estrategia
		 */
		step1_title: () => LocalizedString
		/**
		 * Elige tus fondos o ETFs y asigna el peso ideal para cada uno (ej. 70% MSCI World, 30% Emerging Markets).
		 */
		step1_desc: () => LocalizedString
		/**
		 * Registra tus posiciones
		 */
		step2_title: () => LocalizedString
		/**
		 * Introduce tus participaciones actuales o importa tu historial de transacciones desde tu broker.
		 */
		step2_desc: () => LocalizedString
		/**
		 * Rebalancea
		 */
		step3_title: () => LocalizedString
		/**
		 * Indica cuánto vas a invertir este mes y CoreBalance te dirá exactamente cuánto comprar de cada activo.
		 */
		step3_desc: () => LocalizedString
	}
	how_to_rebalance: {
		/**
		 * Guía de Optimización
		 */
		eyebrow: () => LocalizedString
		/**
		 * ¿Cómo rebalancear mi cartera de
		 */
		title: () => LocalizedString
		/**
		 * MyInvestor gratis
		 */
		title_gradient: () => LocalizedString
		/**
		 * Aprende el proceso paso a paso para optimizar tu asset allocation de forma manual, privada y 100% libre de costes con nuestra calculadora.
		 */
		subtitle: () => LocalizedString
		/**
		 * Configura tus fondos objetivo
		 */
		step1_title: () => LocalizedString
		/**
		 * Entra en CoreBalance y añade tus fondos indexados o ETFs con sus porcentajes objetivo de asignación de activos (ej. 80% MSCI World y 20% Renta Fija Global).
		 */
		step1_desc: () => LocalizedString
		/**
		 * Introduce tus posiciones actuales
		 */
		step2_title: () => LocalizedString
		/**
		 * Registra el saldo o número de participaciones actuales que posees en MyInvestor (o tu comercializadora preferida) para cada activo de tu cartera.
		 */
		step2_desc: () => LocalizedString
		/**
		 * Calcula la aportación o ajuste
		 */
		step3_title: () => LocalizedString
		/**
		 * Introduce el importe de tu aportación periódica mensual o marca la opción para ajustar tus pesos actuales. CoreBalance calculará las compras necesarias al céntimo.
		 */
		step3_desc: () => LocalizedString
		/**
		 * Ejecuta los traspasos o compras gratis
		 */
		step4_title: () => LocalizedString
		/**
		 * Sigue las instrucciones calculadas por CoreBalance y realiza las compras o traspasos (exentos de impuestos en España) directamente en tu cuenta de MyInvestor.
		 */
		step4_desc: () => LocalizedString
		/**
		 * Optimización Fiscal Inteligente
		 */
		note_title: () => LocalizedString
		/**
		 * En España, el rebalanceo mediante {link} entre fondos indexados está {bold} (diferimiento fiscal). CoreBalance te indica las compras óptimas para que aproveches esta ventaja al máximo sin pagar peajes fiscales innecesarios.
		 */
		note_desc: (arg: { bold: string, link: string }) => LocalizedString
		/**
		 * traspasos
		 */
		note_link: () => LocalizedString
		/**
		 * exento de tributación
		 */
		note_bold: () => LocalizedString
	}
	faq: {
		/**
		 * Guía Rápida
		 */
		eyebrow: () => LocalizedString
		/**
		 * Inversión Inteligente:
		 */
		title: () => LocalizedString
		/**
		 * El Rebalanceo
		 */
		title_gradient: () => LocalizedString
		/**
		 * El rebalanceo no es solo una tarea técnica, es la {bold} más potente del inversor indexado. Su objetivo no es maximizar el beneficio a corto plazo, sino {bold2}.
		 */
		subtitle: (arg: { bold: string, bold2: string }) => LocalizedString
		/**
		 * estrategia de defensa
		 */
		subtitle_bold: () => LocalizedString
		/**
		 * controlar el riesgo
		 */
		subtitle_bold2: () => LocalizedString
		/**
		 * Vende caro, compra barato
		 */
		card1_title: () => LocalizedString
		/**
		 * Al rebalancear, trasladas beneficios de los activos que han sobre-rendido hacia aquellos que están infravalorados respecto a tu plan inicial.
		 */
		card1_desc: () => LocalizedString
		/**
		 * Mantén tu perfil de riesgo
		 */
		card2_title: () => LocalizedString
		/**
		 * Si tu plan es 80% acciones y 20% bonos, y las acciones suben hasta el 90%, tu cartera es ahora mucho más volátil de lo que decidiste originalmente.
		 */
		card2_desc: () => LocalizedString
		/**
		 * Traspasos en España
		 */
		card3_title: () => LocalizedString
		/**
		 * Recuerda que en España los traspasos entre fondos de inversión están exentos de tributación, lo que hace que el rebalanceo sea fiscalmente ultra-eficiente.
		 */
		card3_desc: () => LocalizedString
		/**
		 * FAQ
		 */
		faq_eyebrow: () => LocalizedString
		/**
		 * Preguntas Frecuentes
		 */
		faq_title: () => LocalizedString
		/**
		 * ¿Qué es el rebalanceo de cartera?
		 */
		q1_q: () => LocalizedString
		/**
		 * Es el proceso de ajustar los pesos de tus activos para volver a tu estrategia inicial. Con el tiempo, unos activos suben más que otros, alterando tu nivel de riesgo. Rebalancear te obliga a vender caro y comprar barato de forma disciplinada.
		 */
		q1_a: () => LocalizedString
		/**
		 * ¿Cuándo es necesario rebalancear?
		 */
		q2_q: () => LocalizedString
		/**
		 * Existen dos estrategias comunes: por calendario (ej. cada 6 meses) o por bandas de desviación (ej. cuando un activo se desvía más de un 5% de su peso objetivo). CoreBalance te ayuda a identificar estos momentos al instante.
		 */
		q2_a: () => LocalizedString
		/**
		 * ¿Cómo garantiza CoreBalance mi privacidad?
		 */
		q3_q: () => LocalizedString
		/**
		 * A diferencia de otras apps, CoreBalance es 'Local-First'. Tus datos financieros se guardan exclusivamente en tu navegador (IndexedDB). No hay servidores que guarden tu cartera, ni necesitas vincular tus cuentas bancarias.
		 */
		q3_a: () => LocalizedString
		/**
		 * ¿Es compatible con MyInvestor o Indexa Capital?
		 */
		q4_q: () => LocalizedString
		/**
		 * Sí, es el complemento perfecto. Puedes importar tu cartera mediante CSV o introducir tus posiciones manualmente para calcular el rebalanceo exacto que necesitas ejecutar en tu comercializadora.
		 */
		q4_a: () => LocalizedString
	}
	cta: {
		/**
		 * Empieza a optimizar tu cartera
		 */
		title: () => LocalizedString
		/**
		 * hoy mismo
		 */
		title_gradient: () => LocalizedString
		/**
		 * Únete a cientos de inversores que ya confían en CoreBalance para gestionar su patrimonio.
		 */
		subtitle: () => LocalizedString
		/**
		 * No requiere tarjeta de crédito · 100% Privado
		 */
		no_credit: () => LocalizedString
	}
	footer: {
		/**
		 * Tu centro de mandos para una gestión de activos inteligente y equilibrada.
		 */
		tagline: () => LocalizedString
		/**
		 * Privacidad
		 */
		privacy: () => LocalizedString
		/**
		 * Términos
		 */
		terms: () => LocalizedString
		/**
		 * Cookies
		 */
		cookies: () => LocalizedString
		/**
		 * Reportar un error
		 */
		report_bug: () => LocalizedString
		/**
		 * Apoya el proyecto
		 */
		support_project: () => LocalizedString
		/**
		 * Contacto
		 */
		contact: () => LocalizedString
		/**
		 * Hecho con ❤️ para la comunidad inversora.
		 */
		made_with: () => LocalizedString
		/**
		 * CoreBalance es una herramienta informativa. No constituye asesoramiento financiero.
		 */
		legal_notice: () => LocalizedString
	}
	seo: {
		/**
		 * CoreBalance — Rebalancea tu cartera de ETFs y Fondos Indexados
		 */
		title: () => LocalizedString
		/**
		 * La herramienta definitiva para el inversor indexado. Calcula tu rebalanceo en segundos, optimiza tu cartera y mantén tu estrategia bajo control.
		 */
		description: () => LocalizedString
		/**
		 * CoreBalance — Rebalancea tu cartera de ETFs
		 */
		og_title: () => LocalizedString
		/**
		 * Gestiona tu cartera de fondos indexados y ETFs con rebalanceo inteligente y seguimiento en tiempo real.
		 */
		og_description: () => LocalizedString
	}
	dashboard: {
		/**
		 * Valor total
		 */
		total_value: () => LocalizedString
		/**
		 * Variación hoy
		 */
		daily_change: () => LocalizedString
		/**
		 * Cartera
		 */
		portfolio: () => LocalizedString
		/**
		 * Añadir activo
		 */
		add_asset: () => LocalizedString
	}
	common: {
		/**
		 * Cargando...
		 */
		loading: () => LocalizedString
		/**
		 * Ha ocurrido un error inesperado.
		 */
		error_generic: () => LocalizedString
		/**
		 * Reintentar
		 */
		retry: () => LocalizedString
		/**
		 * Guardar
		 */
		save: () => LocalizedString
		/**
		 * Cancelar
		 */
		cancel: () => LocalizedString
		/**
		 * Eliminar
		 */
		'delete': () => LocalizedString
	}
}

export type Formatters = {}
